version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  loader:
    image: curlimages/curl
    container_name: data-loader
    volumes:
      - ./data:/usr/share/elasticsearch/data
    entrypoint: [ "/bin/sh", "-c", "sleep 40 && /usr/share/elasticsearch/data/data_load.sh" ]
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local
